name: 'Cloudflare Workers Deploy'
description: 'Deploy preview and production environments to Cloudflare Workers'
author: 'w3dev'

branding:
  icon: 'upload-cloud'
  color: 'orange'

inputs:
  cloudflare_api_token:
    description: 'Cloudflare API token with Workers edit permission'
    required: true
  cloudflare_account_id:
    description: 'Cloudflare Account ID'
    required: true
  teardown:
    description: 'Delete preview alias when PR closes'
    required: false
    default: 'false'
  package_manager:
    description: 'Package manager to use (bun, npm, pnpm)'
    required: false
    default: 'bun'
  node_version:
    description: 'Node.js version'
    required: false
    default: '22'
  working_directory:
    description: 'Working directory for the build'
    required: false
    default: '.'
  alias_prefix:
    description: 'Prefix for preview alias (e.g., "api" creates api-pr-123-{worker}.workers.dev)'
    required: false
    default: ''
  prebuild_script:
    description: 'Optional script to run before deployment (e.g., configure git author, run codegen)'
    required: false
    default: ''
  install_command:
    description: 'Custom install command (overrides package_manager default)'
    required: false
    default: ''
  github_token:
    description: 'GitHub token for PR comments'
    required: false
    default: ${{ github.token }}
  environment:
    description: 'Deployment environment (preview or production)'
    required: false
    default: 'preview'
  predeploy_script:
    description: 'Optional script to run before deployment'
    required: false
    default: ''
  wrangler_version:
    description: 'Wrangler CLI version (e.g., 4.42.0 or latest)'
    required: false
    default: 'latest'

outputs:
  deployment_url:
    description: 'The Cloudflare Workers deployment URL (production) or preview URL'
    value: ${{ steps.deploy.outputs.url }}
  preview_url:
    description: 'The aliased preview URL (for preview deployments)'
    value: ${{ steps.deploy.outputs.preview_url }}
  version_id:
    description: 'The uploaded version ID'
    value: ${{ steps.deploy.outputs.version_id }}
  pr_number:
    description: 'The PR number (if applicable)'
    value: ${{ steps.context.outputs.pr_number }}

runs:
  using: 'composite'
  steps:
    - name: Determine context
      id: context
      shell: bash
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        ALIAS_PREFIX: ${{ inputs.alias_prefix }}
      run: |
        echo "is_production=${{ inputs.environment == 'production' }}" >> $GITHUB_OUTPUT

        # Skip alias generation for production deployments
        if [ "$ENVIRONMENT" == "production" ]; then
          echo "pr_number=" >> $GITHUB_OUTPUT
          echo "preview_alias=" >> $GITHUB_OUTPUT
        elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          if [ -n "${{ github.event.inputs.pr_number }}" ]; then
            PR_NUM="${{ github.event.inputs.pr_number }}"
            echo "pr_number=$PR_NUM" >> $GITHUB_OUTPUT
            if [ -n "$ALIAS_PREFIX" ]; then
              echo "preview_alias=${ALIAS_PREFIX}-pr-${PR_NUM}" >> $GITHUB_OUTPUT
            else
              echo "preview_alias=pr-${PR_NUM}" >> $GITHUB_OUTPUT
            fi
          else
            echo "pr_number=" >> $GITHUB_OUTPUT
            echo "preview_alias=" >> $GITHUB_OUTPUT
          fi
        else
          PR_NUM="${{ github.event.pull_request.number }}"
          echo "pr_number=$PR_NUM" >> $GITHUB_OUTPUT
          if [ -n "$ALIAS_PREFIX" ]; then
            echo "preview_alias=${ALIAS_PREFIX}-pr-${PR_NUM}" >> $GITHUB_OUTPUT
          else
            echo "preview_alias=pr-${PR_NUM}" >> $GITHUB_OUTPUT
          fi
        fi

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}

    - name: Setup Bun
      if: inputs.package_manager == 'bun'
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Setup pnpm
      if: inputs.package_manager == 'pnpm'
      uses: pnpm/action-setup@v4
      with:
        version: latest

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        INSTALL_CMD: ${{ inputs.install_command }}
        PKG_MANAGER: ${{ inputs.package_manager }}
      run: |
        if [ -n "$INSTALL_CMD" ]; then
          eval "$INSTALL_CMD"
        elif [ "$PKG_MANAGER" == "bun" ]; then
          bun install
        elif [ "$PKG_MANAGER" == "pnpm" ]; then
          pnpm install
        else
          npm ci
        fi

    - name: Install Wrangler CLI
      shell: bash
      env:
        PKG_MANAGER: ${{ inputs.package_manager }}
        WRANGLER_VERSION: ${{ inputs.wrangler_version }}
      run: |
        if [ "$WRANGLER_VERSION" == "latest" ]; then
          PACKAGE="wrangler"
        else
          PACKAGE="wrangler@$WRANGLER_VERSION"
        fi

        if [ "$PKG_MANAGER" == "bun" ]; then
          bun install -g "$PACKAGE"
        elif [ "$PKG_MANAGER" == "pnpm" ]; then
          pnpm install -g "$PACKAGE"
        else
          npm install -g "$PACKAGE"
        fi

    - name: Run prebuild script
      if: inputs.prebuild_script != ''
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: ${{ inputs.prebuild_script }}

    - name: Run predeploy script
      if: inputs.predeploy_script != ''
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: ${{ inputs.predeploy_script }}

    - name: Deploy to Cloudflare Workers
      id: deploy
      if: inputs.teardown != 'true'
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        CLOUDFLARE_API_TOKEN: ${{ inputs.cloudflare_api_token }}
        CLOUDFLARE_ACCOUNT_ID: ${{ inputs.cloudflare_account_id }}
        PREVIEW_ALIAS: ${{ steps.context.outputs.preview_alias }}
        ENVIRONMENT: ${{ inputs.environment }}
      run: |
        if [ "$ENVIRONMENT" == "production" ]; then
          # Production: upload and deploy immediately
          set +e
          OUTPUT=$(wrangler deploy 2>&1)
          EXIT_CODE=$?
          set -e
          echo "$OUTPUT"

          # Check if deployment succeeded (wrangler may return non-zero for warnings)
          if ! echo "$OUTPUT" | grep -qE "(Uploaded|Published)"; then
            echo "Deployment failed with exit code $EXIT_CODE"
            exit 1
          fi

          # Parse production URL from output
          DEPLOYMENT_URL=$(echo "$OUTPUT" | grep -oE 'https://[^[:space:]]+\.workers\.dev' | head -1)
          echo "url=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT
        else
          # Preview: upload version with alias (preserves secrets/bindings)
          if [ -n "$PREVIEW_ALIAS" ]; then
            set +e
            OUTPUT=$(wrangler versions upload --preview-alias "$PREVIEW_ALIAS" 2>&1)
            EXIT_CODE=$?
            set -e
            echo "$OUTPUT"

            # Check if upload succeeded (wrangler may return non-zero for warnings)
            if ! echo "$OUTPUT" | grep -q "Uploaded"; then
              echo "Deployment failed with exit code $EXIT_CODE"
              exit 1
            fi

            # Parse version ID from output
            VERSION_ID=$(echo "$OUTPUT" | grep -oE '[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}' | head -1 || echo "")

            # Parse preview URL from output
            PREVIEW_URL=$(echo "$OUTPUT" | grep -oE 'https://[^[:space:]]+\.workers\.dev' | head -1)

            echo "url=$PREVIEW_URL" >> $GITHUB_OUTPUT
            echo "preview_url=$PREVIEW_URL" >> $GITHUB_OUTPUT
            echo "version_id=$VERSION_ID" >> $GITHUB_OUTPUT
          else
            # No alias provided, fall back to regular deploy
            set +e
            OUTPUT=$(wrangler deploy 2>&1)
            EXIT_CODE=$?
            set -e
            echo "$OUTPUT"

            # Check if deployment succeeded (wrangler may return non-zero for warnings)
            if ! echo "$OUTPUT" | grep -qE "(Uploaded|Published)"; then
              echo "Deployment failed with exit code $EXIT_CODE"
              exit 1
            fi

            DEPLOYMENT_URL=$(echo "$OUTPUT" | grep -oE 'https://[^[:space:]]+\.workers\.dev' | head -1)
            echo "url=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT
          fi
        fi

    - name: Teardown preview alias
      if: inputs.teardown == 'true'
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        CLOUDFLARE_API_TOKEN: ${{ inputs.cloudflare_api_token }}
        CLOUDFLARE_ACCOUNT_ID: ${{ inputs.cloudflare_account_id }}
        PREVIEW_ALIAS: ${{ steps.context.outputs.preview_alias }}
      run: |
        # Note: Cloudflare auto-cleans older aliases (keeps last 1000)
        # There's no direct CLI command to delete an alias
        # The alias will be overwritten on next upload or auto-expire
        echo "Teardown requested for alias: $PREVIEW_ALIAS"
        echo "Note: Cloudflare automatically manages alias cleanup (keeps last 1000 aliases)"
        echo "The alias will be overwritten on next deployment or expire automatically"

    - name: Add deployment summary
      if: inputs.teardown != 'true'
      shell: bash
      env:
        DEPLOYMENT_URL: ${{ steps.deploy.outputs.url }}
        PREVIEW_URL: ${{ steps.deploy.outputs.preview_url }}
        VERSION_ID: ${{ steps.deploy.outputs.version_id }}
        COMMIT_SHA: ${{ github.sha }}
        ENVIRONMENT: ${{ inputs.environment }}
      run: |
        if [ "$ENVIRONMENT" == "production" ]; then
          echo "## Cloudflare Workers Production Deployed" >> $GITHUB_STEP_SUMMARY
        else
          echo "## Cloudflare Workers Preview Deployed" >> $GITHUB_STEP_SUMMARY
        fi
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| | |" >> $GITHUB_STEP_SUMMARY
        echo "|---|---|" >> $GITHUB_STEP_SUMMARY
        echo "| **Deployment URL** | $DEPLOYMENT_URL |" >> $GITHUB_STEP_SUMMARY
        if [ -n "$PREVIEW_URL" ] && [ "$PREVIEW_URL" != "$DEPLOYMENT_URL" ]; then
          echo "| **Preview URL** | $PREVIEW_URL |" >> $GITHUB_STEP_SUMMARY
        fi
        if [ -n "$VERSION_ID" ]; then
          echo "| **Version ID** | \`$VERSION_ID\` |" >> $GITHUB_STEP_SUMMARY
        fi
        echo "| **Commit** | \`$COMMIT_SHA\` |" >> $GITHUB_STEP_SUMMARY

    - name: Comment on PR
      if: steps.context.outputs.pr_number != '' && inputs.environment != 'production' && inputs.teardown != 'true'
      uses: actions/github-script@v7
      env:
        PR_NUMBER: ${{ steps.context.outputs.pr_number }}
        DEPLOYMENT_URL: ${{ steps.deploy.outputs.url }}
        PREVIEW_URL: ${{ steps.deploy.outputs.preview_url }}
        VERSION_ID: ${{ steps.deploy.outputs.version_id }}
        COMMIT_SHA: ${{ github.sha }}
        WORKING_DIR: ${{ inputs.working_directory }}
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const prNumber = parseInt(process.env.PR_NUMBER);
          const deploymentUrl = process.env.DEPLOYMENT_URL;
          const previewUrl = process.env.PREVIEW_URL;
          const versionId = process.env.VERSION_ID;
          const commitSha = process.env.COMMIT_SHA;
          const workingDir = process.env.WORKING_DIR || '.';
          const marker = `<!-- cloudflare-workers-preview-${workingDir} -->`;

          let commentBody = `${marker}

          **Cloudflare Workers Preview Deployed**

          | | |
          |---|---|
          | **Preview URL** | ${deploymentUrl} |`;

          if (versionId) {
            commentBody += `
          | **Version ID** | \`${versionId}\` |`;
          }

          commentBody += `
          | **Commit** | \`${commitSha}\` |
          `;

          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: prNumber,
            per_page: 100
          });

          const existingComment = comments.find(comment =>
            comment.user.login === 'github-actions[bot]' &&
            comment.body.includes(marker)
          );

          if (existingComment) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: existingComment.id,
              body: commentBody
            });
          } else {
            await github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });
          }
